config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'

  end

  resources :topics do
    member do
      get :questions
    end
  end
  resources :customers
  resources :options
  resources :questions
  devise_for :users
  resources :surveys
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :options, dependent: :destroy
  belongs_to :topic
  belongs_to :survey, optional: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions
  belongs_to :topic
  belongs_to :customer
  belongs_to :question, optional: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :questions
  has_many :surveys
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base

  private

    def customer_params
      params.require(:customer).permit(:name)
    end

end

app/controllers/options_controller.rb
class OptionsController < InheritedResources::Base

  private

    def option_params
      params.require(:option).permit(:text, :sort_index)
    end

end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base

  private

    def question_params
      params.require(:question).permit(:text, :topic, :sort_index)
    end

end

app/controllers/surveys_controller.rb
class SurveysController < InheritedResources::Base

  private

  def survey_params
    params.require(:survey).permit(:name, :topic_id, :customer_id, :question_id)
  end

end

app/controllers/topics_controller.rb
class TopicsController < InheritedResources::Base

  def questions
    Rails.logger.info "Questions action called for topic ID: #{params[:id]}"
    
    topic = Topic.find(params[:id])
    Rails.logger.info "Found topic: #{topic.label}"
    
    questions = topic.questions.order(:text)
    Rails.logger.info "Found #{questions.count} questions for topic"
    
    response = questions.select(:id, :text)
    Rails.logger.info "Returning questions: #{response.to_json}"
    
    render json: response
  end

  def show
    @topic = Topic.find(params[:id])
    @questions = @topic.questions
  end

  private

  def topic_params
    params.require(:topic).permit(:key, :label)
  end

end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  private

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_flashes.html.haml
- if flash.any?
  .flashes
    - flash.each do |type, message|
      %div{:class => "flash-#{type}"}= message

app/views/customers/_form.html.haml
= form_for @customer do |f|
  - if @customer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@customer.errors.count, "error")} prohibited this customer from being saved:"
      %ul
        - @customer.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/customers/edit.html.haml
%h1 Editing customer

= render 'form'

= link_to 'Show', @customer
\|
= link_to 'Back', customers_path

app/views/customers/index.html.haml
= turbo_include_tags
%h1 Listing customers

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @customers.each do |customer|
      %tr
        %td= customer.name
        %td= link_to 'Show', customer
        %td= link_to 'Edit', edit_customer_path(customer)
        %td= link_to 'Delete', customer, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }

%br

= link_to 'New Customer', new_customer_path

app/views/customers/new.html.haml
%h1 New customer

= render 'form'

= link_to 'Back', customers_path

app/views/customers/show.html.haml
%p
  %b Name:
  = @customer.name

= link_to 'Edit', edit_customer_path(@customer)
\|
= link_to 'Back', customers_path

app/views/options/_form.html.haml
= form_for @option do |f|
  - if @option.errors.any?
    #error_explanation
      %h2= "#{pluralize(@option.errors.count, "error")} prohibited this option from being saved:"
      %ul
        - @option.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :text
    = f.text_field :text
  .field
    = f.label :sort_index
    = f.number_field :sort_index
  .actions
    = f.submit 'Save'

app/views/options/edit.html.haml
%h1 Editing option

= render 'form'

= link_to 'Show', @option
\|
= link_to 'Back', options_path

app/views/options/index.html.haml
= turbo_include_tags
%h1 Listing options

%table
  %thead
    %tr
      %th Text
      %th Sort index
      %th
      %th
      %th

  %tbody
    - @options.each do |option|
      %tr
        %td= option.text
        %td= option.sort_index
        %td= link_to 'Show', option
        %td= link_to 'Edit', edit_option_path(option)
        %td= link_to 'Destroy', option, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }

%br

= link_to 'New Option', new_option_path

app/views/options/new.html.haml
%h1 New option

= render 'form'

= link_to 'Back', options_path

app/views/options/show.html.haml
%p
  %b Text:
  = @option.text
%p
  %b Sort index:
  = @option.sort_index

= link_to 'Edit', edit_option_path(@option)
\|
= link_to 'Back', options_path

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :text
    = f.text_field :text
  .field
    = f.label :topic
    = f.collection_select :topic_id, Topic.order(:label), :id, :label
  .field
    = f.label :sort_index
    = f.number_field :sort_index
  .actions
    = f.submit 'Save'

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
= turbo_include_tags
%h1 Listing questions

.div{data: { controller: "question-filter" }}
  %select{data: { question_filter_target: "topic", action: "change->question-filter#filterQuestions" }}
    %option{value: ""} Select a topic
    - Topic.all.each do |topic|
      %option{value: topic.id}= topic.label

  %select{data: { question_filter_target: "questions" }, disabled: true}
    %option{value: ""} Select a question

%table
  %thead
    %tr
      %th Text
      %th Topic
      %th Sort index
      %th
      %th
      %th

  %tbody
    - @questions.each do |question|
      %tr
        %td= question.text
        %td= link_to question.topic.label, question.topic
        %td= question.sort_index
        %td= link_to 'Show', question
        %td= link_to 'Edit', edit_question_path(question)
        %td= link_to 'Destroy', question, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }

%br

= link_to 'New Question', new_question_path

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.haml
%p
  %b Text:
  = @question.text
.options
  %p
    %b Options:
  %ol
    - @question.options.order(sort_index: :asc).each do |option|
      %li= option.text

%p
  %b Topic:
  = link_to @question.topic.label, @question.topic
%p
  %b Sort index:
  = @question.sort_index

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path

app/views/surveys/_form.html.haml
= form_for @survey, data: { controller: "question-filter" } do |f|
  - if @survey.errors.any?
    #error_explanation
      %h2= "#{pluralize(@survey.errors.count, "error")} prohibited this survey from being saved:"
      %ul
        - @survey.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :topic_id, "Topic"
    = f.collection_select :topic_id, Topic.order(:label), :id, :label, {}, 
      class: 'topic-select',
      data: {question_filter_target: "topic", action: "change->question-filter#filterQuestions"}

  .field
    = f.label :question_id, "Question"
    = f.collection_select :question_id, [], :id, :text, {}, 
      class: 'questions-select',
      data: { question_filter_target: "questions" },
      disabled: true

  .field
    = f.label :customer_id, "Customer"
    = f.collection_select :customer_id, Customer.order(:name), :id, :name

  .actions
    = f.submit 'Save'

app/views/surveys/edit.html.haml
%h1 Editing survey

= render 'form'

= link_to 'Show', @survey
\|
= link_to 'Back', surveys_path

app/views/surveys/index.html.haml
= turbo_include_tags
%h1 Listing surveys

%table
  %thead
    %tr
      %th Name
      %th Topic
      %th Customer
      %th
      %th
      %th

  %tbody
    - @surveys.each do |survey|
      %tr
        %td= survey.name
        %td= link_to survey.topic.label, survey.topic
        %td= link_to survey.customer.name, survey.customer

        %td= link_to 'Show', survey
        %td= link_to 'Edit', edit_survey_path(survey)
        %td= link_to 'Destroy', survey, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }

%br

= link_to 'New Survey', new_survey_path

app/views/surveys/new.html.haml
%h1 New survey

= render 'form'

= link_to 'Back', surveys_path

app/views/surveys/show.html.haml
%p
  %b Name:
  = @survey.name

%p
  %b Customer:
  = link_to @survey.customer.name, @survey.customer

%p
  %b Topic:
  = link_to @survey.topic.label, @survey.topic

= link_to 'Edit', edit_survey_path(@survey)
\|
= link_to 'Back', surveys_path

app/views/topics/_form.html.haml
= form_for @topic do |f|
  - if @topic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@topic.errors.count, "error")} prohibited this topic from being saved:"
      %ul
        - @topic.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :key
    = f.text_field :key
  .field
    = f.label :label
    = f.text_field :label
  .actions
    = f.submit 'Save'

app/views/topics/edit.html.haml
%h1 Editing topic

= render 'form'

= link_to 'Show', @topic
\|
= link_to 'Back', topics_path

app/views/topics/index.html.haml
= turbo_include_tags
%h1 Listing topics

%table
  %thead
    %tr
      %th Key
      %th Label
      %th
      %th
      %th

  %tbody
    - @topics.each do |topic|
      %tr
        %td= topic.key
        %td= topic.label
        %td= link_to 'Show', topic
        %td= link_to 'Edit', edit_topic_path(topic)
        %td= link_to 'Destroy', topic, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }

%br

= link_to 'New Topic', new_topic_path

app/views/topics/new.html.haml
%h1 New topic

= render 'form'

= link_to 'Back', topics_path

app/views/topics/show.html.erb
<h1><%= @topic.label %></h1>

<div data-controller="question-filter">
  <select data-question-filter-target="topic" data-action="change->question-filter#filterQuestions">
    <option value="">Select a topic</option>
    <% Topic.all.each do |topic| %>
      <option value="<%= topic.id %>"><%= topic.label %></option>
    <% end %>
  </select>

  <select data-question-filter-target="questions" disabled>
    <option value="">Select a question</option>
    <!-- Questions will be populated dynamically -->
  </select>
</div>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Topic</th>
      <th>Sort index</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.text %></td>
        <td><%= link_to question.topic.label, question.topic %></td>
        <td><%= question.sort_index %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/topics/show.html.haml
%p
  %b Key:
  = @topic.key
%p
  %b Label:
  = @topic.label

= link_to 'Edit', edit_topic_path(@topic)
\|
= link_to 'Back', topics_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Email
      %th First name
      %th Last name
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= user.first_name
        %td= user.last_name
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p
  %b Email:
  = @user.email
%p
  %b First name:
  = @user.first_name
%p
  %b Last name:
  = @user.last_name

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path