config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'

  end

  resources :topics do
    member do
      get :questions
    end
  end
  resources :customers
  resources :options
  resources :questions
  devise_for :users
  resources :surveys
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :options, dependent: :destroy
  belongs_to :topic
  belongs_to :survey, optional: true
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions
  belongs_to :topic
  belongs_to :customer
  belongs_to :question, optional: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :questions
  has_many :surveys
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/customers_controller.rb
class CustomersController < InheritedResources::Base

  private

    def customer_params
      params.require(:customer).permit(:name)
    end

end

app/controllers/options_controller.rb
class OptionsController < InheritedResources::Base

  private

    def option_params
      params.require(:option).permit(:text, :sort_index)
    end

end

app/controllers/surveys_controller.rb
class SurveysController < InheritedResources::Base

  private

  def survey_params
    params.require(:survey).permit(:name, :topic_id, :customer_id, :question_id)
  end

end

app/controllers/topics_controller.rb
class TopicsController < InheritedResources::Base

  def questions
    Rails.logger.info "Questions action called for topic ID: #{params[:id]}"
    
    topic = Topic.find(params[:id])
    Rails.logger.info "Found topic: #{topic.label}"
    
    questions = topic.questions.order(:text)
    Rails.logger.info "Found #{questions.count} questions for topic"
    
    response = questions.select(:id, :text)
    Rails.logger.info "Returning questions: #{response.to_json}"
    
    render json: response
  end

  def show
    @topic = Topic.find(params[:id])
    @questions = @topic.questions
  end

  private

  def topic_params
    params.require(:topic).permit(:key, :label)
  end

end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base

  private

    def user_params
      params.require(:user).permit(:email, :first_name, :last_name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SurveyBldr
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    = javascript_include_tag "application", type: "module", defer: true

  %body{ class: "#{controller_name&.dasherize} #{action_name&.dasherize}" }
    .layout
      .header
        %h1 The Survey Builder
        .user-info
          - if current_user
            %span.current-user Logged in as #{current_user.email}
            = link_to 'Logout', sign_out_path, method: :delete
          - else
            = link_to 'Login', sign_in_path
      .main
        .sidebar
          %ul.nav-links
            %li= link_to 'Users', users_path
            %li= link_to 'Customers', customers_path
            %li= link_to 'Topics', topics_path
            %li= link_to 'Surveys', surveys_path
            %li= link_to 'Questions', questions_path
        .content
          = render "flashes"
          = yield